- title: "EU Project"
  key: "EU-H2020-XXX"
  agency: "European Commission - Horizon 2020 Programme"
  category: "Category"
  period: "2023-2027"
  ongoing: 1
  lead: "*Perosn 1* (PI) and *Per Mattsson*"
  member: "1 PhD student"
  selected: 1
  summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus enim, volutpat in lobortis vel, consectetur id nisl. Aenean non velit pellentesque turpis sollicitudin sodales. Nullam in erat ac nisl porta luctus. Maecenas hendrerit suscipit mauris sed vestibulum. Quisque nisi dolor, lobortis non viverra id, dignissim nec felis. Morbi posuere orci et turpis convallis congue. Nullam viverra pharetra purus, eget ultrices urna facilisis at. Etiam ac sapien sit amet erat efficitur finibus. Pellentesque vitae lorem ante."

- title: "PROJECT 1"
  key: "VR2023-PM"
  agency: "Swedish Research Council (Vetenskapsrådet)"
  category: "VR Starting grant within healthcare"
  period: "2024-2027"
  ongoing: 1
  lead: "*Person 2* (PI)"
  member: "1 PhD student, 2 Postdocs"
  selected: 1
  summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus enim, volutpat in lobortis vel, consectetur id nisl. Aenean non velit pellentesque turpis sollicitudin sodales. Nullam in erat ac nisl porta luctus. Maecenas hendrerit suscipit mauris sed vestibulum. Quisque nisi dolor, lobortis non viverra id, dignissim nec felis. Morbi posuere orci et turpis convallis congue. Nullam viverra pharetra purus, eget ultrices urna facilisis at. Etiam ac sapien sit amet erat efficitur finibus. Pellentesque vitae lorem ante."

- title: "EU Project 2"
  key: "EU-H2020-XXX"
  agency: "European Commission - Horizon 2020 Programme"
  category: "Category"
  period: "2018-2022"
  ongoing: 0
  lead: "*Perosn 1* (PI) and *Per Mattsson*"
  member: "1 PhD student"
  selected: 0
  summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam risus enim, volutpat in lobortis vel, consectetur id nisl. Aenean non velit pellentesque turpis sollicitudin sodales. Nullam in erat ac nisl porta luctus. Maecenas hendrerit suscipit mauris sed vestibulum. Quisque nisi dolor, lobortis non viverra id, dignissim nec felis. Morbi posuere orci et turpis convallis congue. Nullam viverra pharetra purus, eget ultrices urna facilisis at. Etiam ac sapien sit amet erat efficitur finibus. Pellentesque vitae lorem ante."